config/routes.rb
Quiz2::Application.routes.draw do

  root 'eatspots#index'
  resources :eatspots
   get 'major', :to => 'eatspots#major'

end

app/models/eatspot.rb
class Eatspot < ActiveRecord::Base
geocoded_by :address
reverse_geocoded_by :inputlattitude, :inputlongitude
after_validation :geocode, :reverse_geocode

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/eatspots_controller.rb
class EatspotsController < ApplicationController
	def index
		@eatspots = Eatspot.all 
	end 

	def new 
		@eatspot = Eatspot.new 
	end 
		def major
		@eatspots = Eatspot.all
	end 

	def create
		Eatspot.create(eatspot_params)
		 redirect_to root_path
		end


		private

		def eatspot_params
		params.require(:eatspot).permit(:name, :description, :address, :inputlattitude,:inputlongitude)
		end 



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/eatspots_helper.rb
module EatspotsHelper
end

app/views/eatspots/index.html.erb
<div class="booyah-box1 col-xs-10 col-xs-offset-1">
	<div>
	<h1>Welcome to Skatespots - a forum for sickest places to skate! </h1>
	</div>
</div>
<br>
<br>


<div class="booyah-box1 col-xs-4 col-xs-offset-4">
	<% @eatspots.each do |eatspot| %>
  <div>
    Name
    <h1><%= eatspot.name %></h1><br />
    Address
    <i><%= eatspot.address %></i><br />
    description
    <p><%= eatspot.description %></p><br />
    input lat
     <p><%= eatspot.inputlattitude %></p><br />
     inout long
      <p><%= eatspot.inputlongitude %></p><br />
      lat
       <p><%= eatspot.latitude %></p><br />
       long
      <p><%= eatspot.longitude %></p><br />
      geo address 
      <p><%= eatspot.geo_address%></p><br/>

  </div>

  <hr />
<% end %>
</div>

app/views/eatspots/major.html.erb
<!DOCTYPE html>
<html>
<head>
 

<div id="map"></div>

  <script src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false"></script>
  <script type="text/javascript">
  
    var locations = <%= @eatspots.collect {|es| [es.name, es.inputlattitude, es.inputlongitude, 4]}.to_json.html_safe %>;
    var map = new google.maps.Map(document.getElementById('map'), {
      zoom: 12,
      center: new google.maps.LatLng(<%= @eatspots.first.inputlattitude %>, <%= @eatspots.first.inputlongitude %>),
      mapTypeId: google.maps.MapTypeId.ROADMAP
    });
    var infowindow = new google.maps.InfoWindow();
    var marker, i;
    for (i = 0; i < locations.length; i++) {  
      marker = new google.maps.Marker({
        position: new google.maps.LatLng(locations[i][1], locations[i][2]),
        map: map
      });
      google.maps.event.addListener(marker, 'click', (function(marker, i) {
        return function() {
          infowindow.setContent(locations[i][0]);
          infowindow.open(map, marker);
        }
      })(marker, i));
    }
  </script>

</div>
</body>
</html>

app/views/eatspots/new.html.erb
<!DOCTYPE html>
<html>
<body>

  

<div class="booyah-box1 col-xs-10 col-xs-offset-1">
  <h1>Where you at </h1>
  <%= simple_form_for @eatspot do |f| %>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :description %>
    <br />
    <%= f.input :inputlattitude, :input_html => {:id => 'lat' } %>
    <%= f.input :inputlongitude, :input_html => {:id => 'lng' } %>
    <%= f.submit 'Create', :class => 'btn btn-primary' %>
  <% end %>

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>

<p> No address, No Problem! Click the button to get your spot.</p>

<button onclick="getLocation()">Find My Spot</button>

<p id="demo"></p>

<script>
var x = document.getElementById("demo");

function getLocation() {
    if (navigator.geolocation) {
        navigator.geolocation.getCurrentPosition(showPosition);
    } else { 
        x.innerHTML = "Geolocation is not supported by this browser.";
    }
}

function showPosition(position) {
  $('#lat').val(position.coords.latitude);
  $('#lng').val(position.coords.longitude);
    x.innerHTML = "Latitude: " + position.coords.latitude + 
    "<br>Longitude: " + position.coords.longitude;  
}
</script>


</body>
</html>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Quiz2</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>


	<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">
      	
        <%= link_to 'Skate Spots', root_path, :class => 'navbar-brand' %> 
      </a>
    </div>

    
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
    <li>
      <%= link_to 'New Place', new_eatspot_path %>
    </li>
    
        <li>
          <%= link_to 'Map', major_path %>
        </li>

    <!---
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
         -->    
    </div>
  </div>
</nav>

<!---
<nav class="navbar navbar-default navbar-fixed-bottom">
  <div class="container-fluid">
    
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Brand</a>
    </div>


    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>
-->
<%= yield %>

</body>
</html>